# Generated by Django 3.1 on 2021-05-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessage',
            name='receiver',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
