# Generated by Django 3.2 on 2021-06-07 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_audittrail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditTrail',
        ),
    ]
