# Generated by Django 3.2 on 2021-06-14 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.IntegerField()),
                ('previous_arrears', models.IntegerField()),
                ('amount_paid', models.IntegerField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('current_arrears', models.IntegerField()),
                ('student_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('year', models.CharField(blank=True, max_length=300, null=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.courses')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.term')),
            ],
        ),
        migrations.CreateModel(
            name='FeesParticular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_payable', models.IntegerField(default=0)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.courses')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.term')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrailFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('item', models.TextField(max_length=300)),
                ('date', models.CharField(max_length=400)),
                ('page', models.CharField(max_length=1000)),
                ('description', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Trail',
                'verbose_name_plural': 'Audit Trail ',
            },
        ),
    ]
