# Generated by Django 3.2 on 2021-06-15 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='registration_number',
            field=models.CharField(max_length=200),
        ),
    ]
