# Generated by Django 3.1 on 2021-05-12 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesParticulars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.courses')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.module')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.term')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.session')),
            ],
            options={
                'verbose_name': 'Fees Particular',
                'verbose_name_plural': 'Fees Particulars',
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=50)),
                ('payment_mthd', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_number_or_mpesa_code', models.CharField(blank=True, max_length=50, null=True)),
                ('prev_arrears', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('current_arrears', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.courses')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.module')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.term')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.session')),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fees Payment',
            },
        ),
    ]
