# Generated by Django 3.2 on 2021-06-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_enrollmentfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentfee',
            name='reg_no',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='Registration_admission_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='Tution_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='activity_fund',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='boarding_hostel_fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='citc_uniform_badge_id_card_t_shirt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='computer_studies',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='electricity_water_and_conservancy',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='evening_classes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='examination',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='income_genarating_act',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='medical_fud_insurance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='miscellaneous',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='production_contracts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='rent_hire',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='repair_and_maintanance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentfee',
            name='sundry_debtors_fees_arrears',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
