# Generated by Django 3.1 on 2021-05-12 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_full_description', models.TextField(max_length=400)),
                ('about_us_img', models.ImageField(upload_to='files')),
                ('gallery1', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery2', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery3', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery4', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery5', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery6', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery7', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery8', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery9', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery10', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery11', models.ImageField(blank=True, null=True, upload_to='files')),
                ('gallery12', models.ImageField(blank=True, null=True, upload_to='files')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
            },
        ),
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_introduction', models.TextField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='files')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accreditation',
                'verbose_name_plural': 'Accreditation',
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_introduction', models.TextField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admission',
                'verbose_name_plural': 'Admission',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email1', models.EmailField(max_length=254)),
                ('email2', models.EmailField(max_length=254)),
                ('phone1', models.IntegerField(blank=True, null=True)),
                ('phone2', models.IntegerField(blank=True, null=True)),
                ('phone3', models.IntegerField(blank=True, null=True)),
                ('box', models.CharField(max_length=50)),
                ('location', models.TextField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_one_text', models.TextField(max_length=400)),
                ('slider_one_image', models.ImageField(blank=True, null=True, upload_to='files')),
                ('slider_two_text', models.TextField(max_length=400)),
                ('slider_two_image', models.ImageField(blank=True, null=True, upload_to='files')),
                ('slider_three_text', models.TextField(max_length=400)),
                ('slider_three_image', models.ImageField(blank=True, null=True, upload_to='files')),
                ('welcome_message', models.TextField(max_length=200)),
                ('director_image', models.ImageField(blank=True, null=True, upload_to='files')),
                ('director_message', models.TextField(max_length=1500)),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Index Page',
                'verbose_name_plural': 'Index Pages',
            },
        ),
        migrations.CreateModel(
            name='MessagesFromVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Messages From Visitor',
                'verbose_name_plural': 'Messages From Visitors',
            },
        ),
        migrations.CreateModel(
            name='NewsEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='files')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'News & Events',
                'verbose_name_plural': 'News & Events',
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField()),
                ('graduation_year', models.IntegerField()),
                ('current_occupation', models.CharField(max_length=1000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.courses')),
            ],
            options={
                'verbose_name': 'Alumni',
                'verbose_name_plural': 'Alumni',
            },
        ),
    ]
