# Generated by Django 3.1 on 2021-05-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_us_full_description',
            field=models.TextField(max_length=1500),
        ),
    ]
