# Generated by Django 3.1 on 2021-05-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomestatement', '0003_auto_20210521_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=50)),
                ('asset_amount', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Asset ',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Liabilities_name', models.CharField(max_length=50)),
                ('Liabilities_amount', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Liabilitie ',
                'verbose_name_plural': 'Liabilities',
            },
        ),
    ]
