# Generated by Django 3.1 on 2021-05-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomestatement', '0005_auto_20210521_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxrate',
            name='active_rate',
            field=models.BooleanField(default=False),
        ),
    ]
