# Generated by Django 3.1 on 2021-05-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomestatement', '0007_taxrate_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expenses',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='revenue',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
