# Generated by Django 3.1 on 2021-05-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomestatement', '0008_auto_20210521_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilities',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
